//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Phone
    {
        public int CustomerPhoneId { get; set; }
        public int CustomerId { get; set; }
        public int PhoneId { get; set; }
        public string CustomerPhoneType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Phone Phone { get; set; }
    }
}
