//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesperson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salesperson()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int SalespersonId { get; set; }
        public string SalespersonFirstName { get; set; }
        public string SalespersonLastName { get; set; }
        public string SalespersonAddress { get; set; }
        public string SalespersonPhoneNumber { get; set; }
        public int LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
